---
- name: Clone oh-my-zsh for users
  tags:
    # Suppress warning: [ANSIBLE0006] git used in place of git module
    # Git module doesn't allow us to set `core.autocrlf=input`.
    - skip_ansible_lint
  become: true
  become_user: '{{ item.username }}'
  # core.autocrlf=input prevents https://github.com/ohmyzsh/ohmyzsh/issues/4402
  ansible.builtin.command: 'git clone -c core.autocrlf=input --depth=1 https://github.com/ohmyzsh/ohmyzsh.git .oh-my-zsh'
  args:
    chdir: '~{{ item.username }}'
    creates: '~{{ item.username }}/.oh-my-zsh'
  loop: "{{ zsh_users }}"
  loop_control:
    label: '{{ item.username }}'
  when: "item.oh_my_zsh is defined"

- name: Set permissions of oh-my-zsh for users
  become: true
  ansible.builtin.file:
    path: '~{{ item.username }}/.oh-my-zsh'
    # Prevent the cloned repository from having insecure permissions. Failing to do
    # so causes compinit() calls to fail with "command not found: compdef" errors
    # for users with insecure umasks (e.g., "002", allowing group writability).
    mode: 'go-w'
    recurse: true
  loop: "{{ zsh_users }}"
  loop_control:
    label: '{{ item.username }}'
  when: "item.oh_my_zsh is defined"
