---
- name: Create fonts directory
  ansible.builtin.file:
    path: "{{ zsh_p10k_fonts_path }}"
    mode: '0755'
    state: directory
  become: true

- name: Copy powerlevel10k recommanded fonts
  ansible.builtin.copy:
    src: "fonts/{{ item }}"
    dest: "{{ zsh_p10k_fonts_path }}/{{ item }}"
    mode: '0644'
  become: true
  loop:
    - MesloLGS NF Bold Italic.ttf
    - MesloLGS NF Bold.ttf
    - MesloLGS NF Italic.ttf
    - MesloLGS NF Regular.ttf
