- name: "INSTALLING - ZEROTIER via SNAP"
  become: true
  community.general.snap:
    name: "zerotier"
    state: present
    classic: true
    channel: "latest/stable"
  register: zerotier_install

- name: "WAITING 1 minutes - For ZeroTier to get online" # noqa:
  ansible.builtin.command: "sleep 60"
  when: zerotier_install.changed
