---
- name: "CREATING - groups for users"
  become: true
  ansible.builtin.group:
    name: "{{ item.username }}"
    state: present
  loop: "{{ users }}"
  loop_control:
    label: "Creating Group: {{ item.username }}"

- name: "CREATING - users"
  become: true
  ansible.builtin.user:
    name: "{{ item.username }}"
    state: present
    password: "{{ item.ssh_pass }}"
    shell: /bin/bash
    group: "{{ item.username }}"
  loop: "{{ users }}"
  loop_control:
    label: "Creating User: {{ item.username }}"
  no_log: true

- name: 'VALIDATING - Auth Key Dir is created: "{{ auth_key_dir }}"'
  become: true
  ansible.builtin.file:
    state: directory
    path: "{{ auth_key_dir }}/"
    owner: root
    group: root
    mode: "0755"

- name: "MOVING - Users' keys to {{ auth_key_dir }}"
  become: true
  ansible.builtin.copy:
    src: "{{ item.username }}.pub"
    dest: "{{ auth_key_dir }}/"
    owner: root
    group: root
    mode: "0644"
  loop: "{{ users }}"

- name: "CREATING - SSHD Config file"
  become: true
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    backup: true
    owner: root
    group: root
    mode: "0644"
  notify:
    - "restart sshd"

- name: "ADDING - sudo users to the Sudoers file"
  become: true
  ansible.builtin.template:
    src: "sudoers.j2"
    dest: "/etc/sudoers.d/sudo-{{ item.username }}"
    owner: root
    group: root
    mode: "0440"
  loop: "{{ users }}"
  when: item.ssh_access is defined

- name: "ADDING - Custom Alias File"
  become: true
  ansible.builtin.template:
    src: "{{ item.custom_alias_file }}"
    dest: "/home/{{ item.username }}/.aliases"
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
    mode: "0644"
  loop: "{{ users }}"
  when: item.custom_alias_file is defined

- name: "ADDING - Custom Functions File"
  become: true
  ansible.builtin.template:
    src: "{{ item.custom_functions_file }}"
    dest: "/home/{{ item.username }}/.custom_functions"
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
    mode: "0644"
  loop: "{{ users }}"
  when: item.custom_functions_file is defined

- name: COPYING - Custom scripts
  become: true
  ansible.builtin.copy:
    src: "custom_scripts"
    dest: "/home/{{ item.username }}/"
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
    mode: "0755"
  loop: "{{ users }}"
